// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fire_boom/domain"
	mock "github.com/stretchr/testify/mock"
)

// PrismaRepository is an autogenerated mock type for the PrismaRepository type
type PrismaRepository struct {
	mock.Mock
}

// CheckExist provides a mock function with given fields: ctx, auth
func (_m *PrismaRepository) CheckExist(ctx context.Context, auth *domain.Prisma) (domain.Prisma, error) {
	ret := _m.Called(ctx, auth)

	var r0 domain.Prisma
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Prisma) domain.Prisma); ok {
		r0 = rf(ctx, auth)
	} else {
		r0 = ret.Get(0).(domain.Prisma)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Prisma) error); ok {
		r1 = rf(ctx, auth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, p
func (_m *PrismaRepository) Create(ctx context.Context, p *domain.Prisma) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Prisma) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PrismaRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx
func (_m *PrismaRepository) Fetch(ctx context.Context) ([]domain.Prisma, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Prisma
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Prisma); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Prisma)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PrismaRepository) GetByID(ctx context.Context, id int64) (domain.Prisma, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.Prisma
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Prisma); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Prisma)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *PrismaRepository) GetByName(ctx context.Context, name string) (domain.Prisma, error) {
	ret := _m.Called(ctx, name)

	var r0 domain.Prisma
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Prisma); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.Prisma)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, p
func (_m *PrismaRepository) Update(ctx context.Context, p *domain.Prisma) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Prisma) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPrismaRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewPrismaRepository creates a new instance of PrismaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPrismaRepository(t mockConstructorTestingTNewPrismaRepository) *PrismaRepository {
	mock := &PrismaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
