// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fire_boom/domain"
	mock "github.com/stretchr/testify/mock"
)

// RoleUseCase is an autogenerated mock type for the RoleUseCase type
type RoleUseCase struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *RoleUseCase) Delete(ctx context.Context, id uint) (int64, error) {
	ret := _m.Called(ctx, id)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindRoles provides a mock function with given fields: ctx
func (_m *RoleUseCase) FindRoles(ctx context.Context) ([]domain.FbRole, error) {
	ret := _m.Called(ctx)

	var r0 []domain.FbRole
	if rf, ok := ret.Get(0).(func(context.Context) []domain.FbRole); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FbRole)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, role
func (_m *RoleUseCase) Store(ctx context.Context, role *domain.FbRole) (int64, error) {
	ret := _m.Called(ctx, role)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *domain.FbRole) int64); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.FbRole) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, role
func (_m *RoleUseCase) Update(ctx context.Context, role *domain.FbRole) (int64, error) {
	ret := _m.Called(ctx, role)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *domain.FbRole) int64); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.FbRole) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRoleUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoleUseCase creates a new instance of RoleUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoleUseCase(t mockConstructorTestingTNewRoleUseCase) *RoleUseCase {
	mock := &RoleUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
