// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fire_boom/domain"
	mock "github.com/stretchr/testify/mock"
)

// StorageBucketUseCase is an autogenerated mock type for the StorageBucketUseCase type
type StorageBucketUseCase struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *StorageBucketUseCase) Delete(ctx context.Context, id uint) (int64, error) {
	ret := _m.Called(ctx, id)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindStorageBucket provides a mock function with given fields: ctx
func (_m *StorageBucketUseCase) FindStorageBucket(ctx context.Context) ([]domain.FbStorageBucket, error) {
	ret := _m.Called(ctx)

	var r0 []domain.FbStorageBucket
	if rf, ok := ret.Get(0).(func(context.Context) []domain.FbStorageBucket); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FbStorageBucket)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *StorageBucketUseCase) GetByID(ctx context.Context, id uint) (domain.FbStorageBucket, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.FbStorageBucket
	if rf, ok := ret.Get(0).(func(context.Context, uint) domain.FbStorageBucket); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.FbStorageBucket)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, f
func (_m *StorageBucketUseCase) Store(ctx context.Context, f *domain.FbStorageBucket) (int64, error) {
	ret := _m.Called(ctx, f)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *domain.FbStorageBucket) int64); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.FbStorageBucket) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, f
func (_m *StorageBucketUseCase) Update(ctx context.Context, f *domain.FbStorageBucket) (int64, error) {
	ret := _m.Called(ctx, f)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *domain.FbStorageBucket) int64); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.FbStorageBucket) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStorageBucketUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorageBucketUseCase creates a new instance of StorageBucketUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorageBucketUseCase(t mockConstructorTestingTNewStorageBucketUseCase) *StorageBucketUseCase {
	mock := &StorageBucketUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
